/**
 * BASE Templates - 10 Variations
 * Base L2 chain theme (blue/cyan/orange)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'base', name: 'Base', primary: '#0052FF', secondary: '#00D4FF', accent: '#FF6B35', background: '#0a0f1c', text: '#ffffff', glow: '#0052FF' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const baseBanner001: SVGTemplate = { id: 'base-banner-001', name: 'Base Standard Banner', category: 'base', description: 'Standard Base L2 banner', palette, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['base', 'banner', 'l2'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'base', userData: data, gaugeLabel: 'L2 STATUS', gaugeValue: 'SYNCED', badgeText: 'BASE BUILDER' }) };

export const baseBanner002: SVGTemplate = { id: 'base-banner-002', name: 'Base Builder', category: 'base', description: 'Builder edition', palette: { ...palette, accent: '#00FF00' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['base', 'banner', 'builder'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'base', userData: data, gaugeLabel: '🔨 BUILD STATUS', gaugeValue: 'SHIPPING', badgeText: '🔨 BASE BUILDER', customPalette: { accent: '#00FF00' } }) };

export const baseBanner003: SVGTemplate = { id: 'base-banner-003', name: 'Base Onchain Summer', category: 'base', description: 'Onchain Summer edition', palette: { ...palette, primary: '#FF6B35', secondary: '#FFD700' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['base', 'banner', 'summer'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'base', userData: data, gaugeLabel: '☀️ ONCHAIN', gaugeValue: 'SUMMER', badgeText: '☀️ ONCHAIN SUMMER', customPalette: { primary: '#FF6B35', secondary: '#FFD700' } }) };

export const baseBanner004: SVGTemplate = { id: 'base-banner-004', name: 'Base L2 Protocol', category: 'base', description: 'L2 protocol edition', palette, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['base', 'banner', 'protocol'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'base', userData: data, gaugeLabel: 'L2 PROTOCOL', gaugeValue: 'ACTIVE', badgeText: 'L2 PROTOCOL' }) };

export const baseBanner005: SVGTemplate = { id: 'base-banner-005', name: 'Base OP Stack', category: 'base', description: 'Optimism stack edition', palette: { ...palette, primary: '#FF0420' }, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['base', 'banner', 'op'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'base', userData: data, gaugeLabel: 'OP STACK', gaugeValue: 'BASED', badgeText: '🔴 OP STACK', customPalette: { primary: '#FF0420' } }) };

export const baseCard001: SVGTemplate = { id: 'base-card-001', name: 'Base Card', category: 'base', description: 'Square Base card', palette, animations: ['pulse', 'gradient'], layout: 'card', width: 400, height: 400, tags: ['base', 'card'],
  generate: (data: UserData) => { const w=400,h=400,uid=`base-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Base User';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔵 BASE L2',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><circle r="50" fill="${palette.primary}" opacity="0.3"/><text y="15" text-anchor="middle" style="font-family:'Arial',sans-serif;font-size:36px;fill:#fff;font-weight:bold">B</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="280" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-size:12px;fill:${palette.secondary}">VOT BALANCE • CHAIN:8453</text>${generateFooter({address:data.address,networkLabel:'BASE MAINNET',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const baseCard002: SVGTemplate = { id: 'base-card-002', name: 'Base Builder Card', category: 'base', description: 'Tall builder card', palette, animations: ['pulse', 'float'], layout: 'card', width: 400, height: 500, tags: ['base', 'card', 'builder'],
  generate: (data: UserData) => { const w=400,h=500,uid=`base-b-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Base Builder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔨 BASE BUILDER',width:w,palette,yOffset:25})}<g transform="translate(${w/2},120)"><circle r="55" fill="${palette.primary}" opacity="0.2"/><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:45px">🔨</text></g><text x="${w/2}" y="205" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="230" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,260)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">BUILD STATUS</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">🚀 SHIPPING</text></g></g><g transform="translate(30,360)"><rect width="340" height="60" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">BUILDER BADGES</text><g transform="translate(0,40)"><text x="50" text-anchor="middle" style="font-size:16px">🔵</text><text x="120" text-anchor="middle" style="font-size:16px">🔨</text><text x="190" text-anchor="middle" style="font-size:16px">⚡</text><text x="260" text-anchor="middle" style="font-size:16px">🚀</text><text x="310" text-anchor="middle" style="font-size:16px">💎</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const baseBadge001: SVGTemplate = { id: 'base-badge-001', name: 'Base Badge', category: 'base', description: 'Compact Base badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['base', 'badge'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'Base User').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.3"><animate attributeName="opacity" values="0.3;0.4;0.3" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-family:'Arial',sans-serif;font-size:24px;fill:#fff;font-weight:bold">B</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">BASE L2</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">Chain ID: 8453 • Mainnet</text>`,w,h); }};

export const baseBadge002: SVGTemplate = { id: 'base-badge-002', name: 'Base Onchain Badge', category: 'base', description: 'Circular onchain badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['base', 'badge', 'onchain'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="base-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#base-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="15s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.3"/><text x="100" y="98" text-anchor="middle" style="font-family:'Arial',sans-serif;font-size:36px;fill:#fff;font-weight:bold">B</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:12px;fill:${palette.primary};font-weight:bold">ONCHAIN</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:1px">BASE L2</text>`,w,h); }};

export const baseShowcase001: SVGTemplate = { id: 'base-showcase-001', name: 'Base Showcase', category: 'base', description: 'Full Base showcase', palette, animations: ['pulse', 'gradient', 'float'], layout: 'dashboard', width: 600, height: 600, tags: ['base', 'showcase'],
  generate: (data: UserData) => { const w=600,h=600,uid=`base-sh-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Base User';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔵 BASE SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">BASE L2 NETWORK</text><g transform="translate(${w/2},190)"><circle r="85" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="85;90;85" dur="2s" repeatCount="indefinite"/></circle><circle r="70" fill="${palette.primary}" opacity="0.25"/><text y="25" text-anchor="middle" style="font-family:'Arial',sans-serif;font-size:60px;fill:#fff;font-weight:bold">B</text></g><text x="${w/2}" y="310" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="335" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,370)">${generateGauge({label:'VOT BALANCE',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'L2 STATUS',value:'SYNCED',subValue:'8453',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-l2`})}</g><g transform="translate(50,510)"><rect width="${w-100}" height="50" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">NETWORK FEATURES</text><g transform="translate(0,38)"><text x="60" text-anchor="middle" style="font-size:16px">⚡</text><text x="140" text-anchor="middle" style="font-size:16px">🔒</text><text x="220" text-anchor="middle" style="font-size:16px">💰</text><text x="300" text-anchor="middle" style="font-size:16px">🔵</text><text x="380" text-anchor="middle" style="font-size:16px">🚀</text><text x="440" text-anchor="middle" style="font-size:16px">🔨</text></g></g>${generateFooter({address:data.address,networkLabel:'BASE • L2 • CHAIN:8453',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const baseTemplates: SVGTemplate[] = [baseBanner001, baseBanner002, baseBanner003, baseBanner004, baseBanner005, baseCard001, baseCard002, baseBadge001, baseBadge002, baseShowcase001];
export default baseTemplates;
