/**
 * DEFI Templates - 10 Variations
 * Finance theme (green/teal/gold)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'defi', name: 'DeFi', primary: '#00D4AA', secondary: '#20B2AA', accent: '#FFD700', background: '#0a1a1a', text: '#ffffff', glow: '#00D4AA' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const defiBanner001: SVGTemplate = { id: 'defi-banner-001', name: 'DeFi Standard Banner', category: 'defi', description: 'Standard DeFi banner', palette, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['defi', 'banner', 'finance'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'defi', userData: data, gaugeLabel: 'DEFI STATUS', gaugeValue: 'ACTIVE', badgeText: 'DEFI PROTOCOL' }) };

export const defiBanner002: SVGTemplate = { id: 'defi-banner-002', name: 'DeFi Yield Farmer', category: 'defi', description: 'Yield farmer banner', palette: { ...palette, accent: '#32CD32' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['defi', 'banner', 'yield'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'defi', userData: data, gaugeLabel: '🌾 YIELD', gaugeValue: 'FARMING', badgeText: '🌾 YIELD FARMER', customPalette: { accent: '#32CD32' } }) };

export const defiBanner003: SVGTemplate = { id: 'defi-banner-003', name: 'DeFi LP Provider', category: 'defi', description: 'LP provider banner', palette: { ...palette, primary: '#00BFFF', accent: '#87CEEB' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['defi', 'banner', 'lp'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'defi', userData: data, gaugeLabel: '💧 LP STATUS', gaugeValue: 'PROVIDED', badgeText: '💧 LP PROVIDER', customPalette: { primary: '#00BFFF', accent: '#87CEEB' } }) };

export const defiBanner004: SVGTemplate = { id: 'defi-banner-004', name: 'DeFi Trader', category: 'defi', description: 'Trader banner', palette: { ...palette, primary: '#FF6B6B', accent: '#FFD93D' }, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['defi', 'banner', 'trader'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'defi', userData: data, gaugeLabel: '📈 TRADER', gaugeValue: 'ACTIVE', badgeText: '📈 DEFI TRADER', customPalette: { primary: '#FF6B6B', accent: '#FFD93D' } }) };

export const defiBanner005: SVGTemplate = { id: 'defi-banner-005', name: 'DeFi TVL', category: 'defi', description: 'TVL focused banner', palette, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['defi', 'banner', 'tvl'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'defi', userData: data, gaugeLabel: '🔒 TVL', gaugeValue: 'LOCKED', badgeText: '🔒 TVL LOCKED' }) };

export const defiCard001: SVGTemplate = { id: 'defi-card-001', name: 'DeFi Card', category: 'defi', description: 'Square DeFi card', palette, animations: ['pulse', 'gradient'], layout: 'card', width: 400, height: 400, tags: ['defi', 'card', 'finance'],
  generate: (data: UserData) => { const w=400,h=400,uid=`defi-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'DeFi User';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'📊 DEFI',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><circle r="50" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:40px">📊</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="280" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-size:12px;fill:${palette.secondary}">VOT BALANCE • DEFI ACTIVE</text>${generateFooter({address:data.address,networkLabel:'DEFI • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const defiCard002: SVGTemplate = { id: 'defi-card-002', name: 'DeFi Portfolio Card', category: 'defi', description: 'Tall portfolio card', palette, animations: ['pulse', 'float'], layout: 'card', width: 400, height: 500, tags: ['defi', 'card', 'portfolio'],
  generate: (data: UserData) => { const w=400,h=500,uid=`defi-p-${Date.now()}`,vot=data.holdings?.votBalance||'0',maxx=data.holdings?.maxxBalance||'0',name=data.displayName||data.ensName||'DeFi User';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'💰 PORTFOLIO',width:w,palette,yOffset:25})}<g transform="translate(${w/2},115)"><circle r="50" fill="${palette.primary}" opacity="0.15"/><circle r="45" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle><text y="15" text-anchor="middle" style="font-size:40px">💰</text></g><text x="${w/2}" y="195" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="218" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,245)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(vot)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">MAXX BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:#ff6b6b;font-weight:bold">${fmtBal(maxx)}</text></g></g><g transform="translate(30,345)"><rect width="340" height="75" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">DEFI FEATURES</text><g transform="translate(0,45)"><text x="50" text-anchor="middle" style="font-size:14px">📊</text><text x="120" text-anchor="middle" style="font-size:14px">💧</text><text x="190" text-anchor="middle" style="font-size:14px">🌾</text><text x="260" text-anchor="middle" style="font-size:14px">🔒</text><text x="310" text-anchor="middle" style="font-size:14px">💰</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const defiBadge001: SVGTemplate = { id: 'defi-badge-001', name: 'DeFi Badge', category: 'defi', description: 'Compact DeFi badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['defi', 'badge', 'finance'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'DeFi User').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">📊</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">DEFI PROTOCOL</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">Yield • LP • Trading</text>`,w,h); }};

export const defiBadge002: SVGTemplate = { id: 'defi-badge-002', name: 'DeFi Yield Badge', category: 'defi', description: 'Circular yield badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['defi', 'badge', 'yield'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="defi-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#defi-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="15s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">🌾</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">YIELD</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.accent};letter-spacing:1px">FARMING</text>`,w,h); }};

export const defiShowcase001: SVGTemplate = { id: 'defi-showcase-001', name: 'DeFi Showcase', category: 'defi', description: 'Full DeFi showcase', palette, animations: ['pulse', 'gradient', 'float'], layout: 'dashboard', width: 600, height: 600, tags: ['defi', 'showcase', 'finance'],
  generate: (data: UserData) => { const w=600,h=600,uid=`defi-sh-${Date.now()}`,vot=data.holdings?.votBalance||'0',maxx=data.holdings?.maxxBalance||'0',name=data.displayName||data.ensName||'DeFi User';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'📊 DEFI SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">DECENTRALIZED FINANCE</text><g transform="translate(${w/2},185)"><circle r="80" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="80;85;80" dur="2s" repeatCount="indefinite"/></circle><circle r="70" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle><text y="20" text-anchor="middle" style="font-size:60px">📊</text></g><text x="${w/2}" y="300" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="325" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,365)">${generateGauge({label:'VOT BALANCE',value:fmtBal(vot),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'MAXX BALANCE',value:fmtBal(maxx),subValue:'MAXX',cx:w-150,cy:60,radius:50,palette:{...palette,primary:'#ff6b6b'},uniqueId:`${uid}-maxx`})}</g><g transform="translate(50,505)"><rect width="${w-100}" height="55" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">DEFI FEATURES</text><g transform="translate(0,40)"><text x="55" text-anchor="middle" style="font-size:16px">📊</text><text x="130" text-anchor="middle" style="font-size:16px">💧</text><text x="205" text-anchor="middle" style="font-size:16px">🌾</text><text x="280" text-anchor="middle" style="font-size:16px">🔒</text><text x="355" text-anchor="middle" style="font-size:16px">💰</text><text x="430" text-anchor="middle" style="font-size:16px">📈</text></g></g>${generateFooter({address:data.address,networkLabel:'DEFI • BASE • VOT • MAXX',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const defiTemplates: SVGTemplate[] = [defiBanner001, defiBanner002, defiBanner003, defiBanner004, defiBanner005, defiCard001, defiCard002, defiBadge001, defiBadge002, defiShowcase001];
export default defiTemplates;
