/**
 * ENS Templates - 10 Variations
 * Identity theme (blue/cyan/sky)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'ens', name: 'ENS', primary: '#5298FF', secondary: '#44BCF0', accent: '#7FD4FF', background: '#0d1117', text: '#ffffff', glow: '#5298FF' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const ensBanner001: SVGTemplate = { id: 'ens-banner-001', name: 'ENS Identity Banner', category: 'ens', description: 'Standard ENS identity banner', palette, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['ens', 'banner', 'identity'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'ens', userData: data, gaugeLabel: 'ENS STATUS', gaugeValue: 'RESOLVED', badgeText: 'ENS IDENTITY' }) };

export const ensBanner002: SVGTemplate = { id: 'ens-banner-002', name: 'ENS Primary Name', category: 'ens', description: 'Primary name banner', palette: { ...palette, accent: '#00FF88' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['ens', 'banner', 'primary'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'ens', userData: data, gaugeLabel: '🔷 PRIMARY', gaugeValue: 'SET', badgeText: '🔷 PRIMARY NAME', customPalette: { accent: '#00FF88' } }) };

export const ensBanner003: SVGTemplate = { id: 'ens-banner-003', name: 'ENS Subdomain', category: 'ens', description: 'Subdomain banner', palette: { ...palette, primary: '#00BFFF' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['ens', 'banner', 'subdomain'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'ens', userData: data, gaugeLabel: 'SUBDOMAIN', gaugeValue: 'ACTIVE', badgeText: 'ENS SUBDOMAIN', customPalette: { primary: '#00BFFF' } }) };

export const ensBanner004: SVGTemplate = { id: 'ens-banner-004', name: 'ENS Avatar', category: 'ens', description: 'Avatar focused banner', palette: { ...palette, accent: '#FF6B6B' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['ens', 'banner', 'avatar'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'ens', userData: data, gaugeLabel: '🖼️ AVATAR', gaugeValue: 'SET', badgeText: '🖼️ ENS AVATAR', customPalette: { accent: '#FF6B6B' } }) };

export const ensBanner005: SVGTemplate = { id: 'ens-banner-005', name: 'ENS Records', category: 'ens', description: 'Records focused banner', palette, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['ens', 'banner', 'records'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'ens', userData: data, gaugeLabel: 'RECORDS', gaugeValue: 'SYNCED', badgeText: 'ENS RECORDS' }) };

export const ensCard001: SVGTemplate = { id: 'ens-card-001', name: 'ENS Identity Card', category: 'ens', description: 'Square identity card', palette, animations: ['pulse', 'gradient'], layout: 'card', width: 400, height: 400, tags: ['ens', 'card', 'identity'],
  generate: (data: UserData) => { const w=400,h=400,uid=`ens-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',ens=data.ensName||'anonymous.eth';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔷 ENS IDENTITY',width:w,palette,yOffset:25})}<g transform="translate(${w/2},130)"><circle r="55" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:40px">🔷</text></g><text x="${w/2}" y="220" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.primary};font-weight:bold">${ens.toUpperCase()}</text><text x="${w/2}" y="275" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:28px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)} VOT</text><text x="${w/2}" y="300" text-anchor="middle" style="font-size:11px;fill:${palette.secondary}">ENS VERIFIED • RESOLVER ACTIVE</text>${generateFooter({address:data.address,networkLabel:'ENS • ETHEREUM',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const ensCard002: SVGTemplate = { id: 'ens-card-002', name: 'ENS Profile Card', category: 'ens', description: 'Tall profile card with records', palette, animations: ['pulse', 'float'], layout: 'card', width: 400, height: 500, tags: ['ens', 'card', 'profile'],
  generate: (data: UserData) => { const w=400,h=500,uid=`ens-p-${Date.now()}`,bal=data.holdings?.votBalance||'0',ens=data.ensName||'anonymous.eth';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔷 ENS PROFILE',width:w,palette,yOffset:25})}<g transform="translate(${w/2},115)"><circle r="50" fill="${palette.primary}" opacity="0.15"/><circle r="45" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle><text y="15" text-anchor="middle" style="font-size:40px">🔷</text></g><text x="${w/2}" y="195" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.primary};font-weight:bold">${ens}</text><text x="${w/2}" y="218" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,245)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">RESOLVER</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">✓ ACTIVE</text></g></g><g transform="translate(30,345)"><rect width="340" height="75" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">TEXT RECORDS</text><g transform="translate(0,40)"><text x="50" text-anchor="middle" style="font-size:14px">🔷</text><text x="120" text-anchor="middle" style="font-size:14px">🖼️</text><text x="190" text-anchor="middle" style="font-size:14px">📧</text><text x="260" text-anchor="middle" style="font-size:14px">🌐</text><text x="310" text-anchor="middle" style="font-size:14px">💬</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const ensBadge001: SVGTemplate = { id: 'ens-badge-001', name: 'ENS Badge', category: 'ens', description: 'Compact ENS badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['ens', 'badge', 'identity'],
  generate: (data: UserData) => { const w=300,h=100,ens=data.ensName||'anonymous.eth';
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">🔷</text></g><text x="100" y="40" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">${ens}</text><text x="100" y="62" style="font-size:11px;fill:${palette.text}">ENS Identity</text><text x="100" y="82" style="font-size:9px;fill:${palette.secondary}">✓ Verified • Resolver Active</text>`,w,h); }};

export const ensBadge002: SVGTemplate = { id: 'ens-badge-002', name: 'ENS Verified Badge', category: 'ens', description: 'Circular verified badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['ens', 'badge', 'verified'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="ens-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#ens-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="15s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">🔷</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">ENS</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.accent};letter-spacing:1px">VERIFIED</text>`,w,h); }};

export const ensShowcase001: SVGTemplate = { id: 'ens-showcase-001', name: 'ENS Identity Showcase', category: 'ens', description: 'Full ENS showcase', palette, animations: ['pulse', 'gradient', 'float'], layout: 'dashboard', width: 600, height: 600, tags: ['ens', 'showcase', 'identity'],
  generate: (data: UserData) => { const w=600,h=600,uid=`ens-sh-${Date.now()}`,bal=data.holdings?.votBalance||'0',ens=data.ensName||'anonymous.eth';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔷 ENS SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">ETHEREUM NAME SERVICE</text><g transform="translate(${w/2},185)"><circle r="80" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="80;85;80" dur="2s" repeatCount="indefinite"/></circle><circle r="70" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle><text y="20" text-anchor="middle" style="font-size:60px">🔷</text></g><text x="${w/2}" y="300" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:24px;fill:${palette.primary};font-weight:bold">${ens}</text><text x="${w/2}" y="325" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,365)">${generateGauge({label:'VOT BALANCE',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'ENS STATUS',value:'ACTIVE',subValue:'✓',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-ens`})}</g><g transform="translate(50,505)"><rect width="${w-100}" height="55" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">ENS RECORDS</text><g transform="translate(0,40)"><text x="55" text-anchor="middle" style="font-size:16px">🔷</text><text x="130" text-anchor="middle" style="font-size:16px">🖼️</text><text x="205" text-anchor="middle" style="font-size:16px">📧</text><text x="280" text-anchor="middle" style="font-size:16px">🌐</text><text x="355" text-anchor="middle" style="font-size:16px">💬</text><text x="430" text-anchor="middle" style="font-size:16px">🔑</text></g></g>${generateFooter({address:data.address,networkLabel:'ENS • ETHEREUM • L1',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const ensTemplates: SVGTemplate[] = [ensBanner001, ensBanner002, ensBanner003, ensBanner004, ensBanner005, ensCard001, ensCard002, ensBadge001, ensBadge002, ensShowcase001];
export default ensTemplates;
