/**
 * FARCASTER Templates - 10 Variations
 * Social protocol theme (purple/violet/cyan)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'farcaster', name: 'Farcaster', primary: '#8B5CF6', secondary: '#A78BFA', accent: '#00ffcc', background: '#0f0a1a', text: '#ffffff', glow: '#8B5CF6' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const farcasterBanner001: SVGTemplate = { id: 'farcaster-banner-001', name: 'Farcaster Social Banner', category: 'farcaster', description: 'Standard Farcaster banner', palette, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['farcaster', 'banner', 'social'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'farcaster', userData: data, gaugeLabel: 'SOCIAL STATUS', gaugeValue: 'ONLINE', badgeText: 'FARCASTER' }) };

export const farcasterBanner002: SVGTemplate = { id: 'farcaster-banner-002', name: 'Farcaster Verified', category: 'farcaster', description: 'Verified user banner', palette: { ...palette, accent: '#00ff88' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['farcaster', 'banner', 'verified'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'farcaster', userData: data, gaugeLabel: '✓ VERIFIED', gaugeValue: 'ACTIVE', badgeText: '✓ VERIFIED USER', customPalette: { accent: '#00ff88' } }) };

export const farcasterBanner003: SVGTemplate = { id: 'farcaster-banner-003', name: 'Farcaster Power User', category: 'farcaster', description: 'Power user banner', palette: { ...palette, primary: '#FF6B6B', accent: '#FFD93D' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['farcaster', 'banner', 'power'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'farcaster', userData: data, gaugeLabel: '⚡ POWER USER', gaugeValue: 'ELITE', badgeText: '⚡ POWER USER', customPalette: { primary: '#FF6B6B', accent: '#FFD93D' } }) };

export const farcasterBanner004: SVGTemplate = { id: 'farcaster-banner-004', name: 'Farcaster Frame', category: 'farcaster', description: 'Frame developer banner', palette: { ...palette, primary: '#00D4FF' }, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['farcaster', 'banner', 'frame'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'farcaster', userData: data, gaugeLabel: '🖼️ FRAME DEV', gaugeValue: 'ACTIVE', badgeText: '🖼️ FRAME BUILDER', customPalette: { primary: '#00D4FF' } }) };

export const farcasterBanner005: SVGTemplate = { id: 'farcaster-banner-005', name: 'Farcaster Cast', category: 'farcaster', description: 'Cast focused banner', palette, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['farcaster', 'banner', 'cast'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'farcaster', userData: data, gaugeLabel: '💬 CASTS', gaugeValue: 'ACTIVE', badgeText: '💬 CASTER' }) };

export const farcasterCard001: SVGTemplate = { id: 'farcaster-card-001', name: 'Farcaster Social Card', category: 'farcaster', description: 'Square social card', palette, animations: ['pulse', 'float'], layout: 'card', width: 400, height: 400, tags: ['farcaster', 'card', 'social'],
  generate: (data: UserData) => { const w=400,h=400,uid=`fc-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'FC User',fc=data.links?.farcaster||'user';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'💜 FARCASTER',width:w,palette,yOffset:25})}<g transform="translate(${w/2},130)"><circle r="55" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:45px">💜</text></g><text x="${w/2}" y="215" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="240" text-anchor="middle" style="font-size:14px;fill:${palette.primary}">@${fc}</text><text x="${w/2}" y="290" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:28px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)} VOT</text>${generateFooter({address:data.address,networkLabel:'FARCASTER • FIP-2',width:w,height:h,palette,bottomOffset:25,socialBadge:`@${fc}`})}`,w,h); }};

export const farcasterCard002: SVGTemplate = { id: 'farcaster-card-002', name: 'Farcaster Profile Card', category: 'farcaster', description: 'Tall profile card', palette, animations: ['pulse', 'float', 'gradient'], layout: 'card', width: 400, height: 500, tags: ['farcaster', 'card', 'profile'],
  generate: (data: UserData) => { const w=400,h=500,uid=`fc-p-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'FC User',fc=data.links?.farcaster||'user';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'💜 FC PROFILE',width:w,palette,yOffset:25})}<g transform="translate(${w/2},115)"><circle r="50" fill="${palette.primary}" opacity="0.15"/><circle r="45" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle><text y="15" text-anchor="middle" style="font-size:40px">💜</text></g><text x="${w/2}" y="195" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="220" text-anchor="middle" style="font-size:14px;fill:${palette.primary}">@${fc}</text><g transform="translate(30,250)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">STATUS</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">✓ ACTIVE</text></g></g><g transform="translate(30,350)"><rect width="340" height="70" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="20" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">SOCIAL FEATURES</text><g transform="translate(0,45)"><text x="50" text-anchor="middle" style="font-size:14px">💬</text><text x="120" text-anchor="middle" style="font-size:14px">👥</text><text x="190" text-anchor="middle" style="font-size:14px">🖼️</text><text x="260" text-anchor="middle" style="font-size:14px">⚡</text><text x="310" text-anchor="middle" style="font-size:14px">💜</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25,socialBadge:`@${fc}`})}`,w,h); }};

export const farcasterBadge001: SVGTemplate = { id: 'farcaster-badge-001', name: 'FC Badge', category: 'farcaster', description: 'Compact FC badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['farcaster', 'badge', 'fc'],
  generate: (data: UserData) => { const w=300,h=100,fc=data.links?.farcaster||'user';
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">💜</text></g><text x="100" y="40" style="font-family:'Orbitron',sans-serif;font-size:16px;fill:${palette.text};font-weight:bold">@${fc}</text><text x="100" y="65" style="font-size:11px;fill:${palette.primary}">FARCASTER</text><text x="100" y="85" style="font-size:9px;fill:${palette.secondary}">Social Protocol • Verified</text>`,w,h); }};

export const farcasterBadge002: SVGTemplate = { id: 'farcaster-badge-002', name: 'FC Verified Badge', category: 'farcaster', description: 'Circular verified badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['farcaster', 'badge', 'verified'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="fc-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#fc-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="15s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">💜</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:12px;fill:${palette.primary};font-weight:bold">FARCASTER</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.accent};letter-spacing:1px">✓ VERIFIED</text>`,w,h); }};

export const farcasterShowcase001: SVGTemplate = { id: 'farcaster-showcase-001', name: 'Farcaster Showcase', category: 'farcaster', description: 'Full Farcaster showcase', palette, animations: ['pulse', 'float', 'gradient'], layout: 'dashboard', width: 600, height: 600, tags: ['farcaster', 'showcase', 'social'],
  generate: (data: UserData) => { const w=600,h=600,uid=`fc-sh-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'FC User',fc=data.links?.farcaster||'user';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'💜 FARCASTER SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">SOCIAL PROTOCOL</text><g transform="translate(${w/2},185)"><circle r="80" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="80;85;80" dur="2s" repeatCount="indefinite"/></circle><circle r="70" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle><text y="20" text-anchor="middle" style="font-size:60px">💜</text></g><text x="${w/2}" y="300" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="325" text-anchor="middle" style="font-size:14px;fill:${palette.primary}">@${fc}</text><g transform="translate(80,365)">${generateGauge({label:'VOT BALANCE',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'SOCIAL SCORE',value:'100',subValue:'POINTS',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-social`})}</g><g transform="translate(50,505)"><rect width="${w-100}" height="55" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">SOCIAL FEATURES</text><g transform="translate(0,40)"><text x="55" text-anchor="middle" style="font-size:16px">💬</text><text x="130" text-anchor="middle" style="font-size:16px">👥</text><text x="205" text-anchor="middle" style="font-size:16px">🖼️</text><text x="280" text-anchor="middle" style="font-size:16px">⚡</text><text x="355" text-anchor="middle" style="font-size:16px">💜</text><text x="430" text-anchor="middle" style="font-size:16px">🔔</text></g></g>${generateFooter({address:data.address,networkLabel:'FARCASTER • FIP-2 • SOCIAL',width:w,height:h,palette,bottomOffset:25,socialBadge:`@${fc}`})}`,w,h); }};

export const farcasterTemplates: SVGTemplate[] = [farcasterBanner001, farcasterBanner002, farcasterBanner003, farcasterBanner004, farcasterBanner005, farcasterCard001, farcasterCard002, farcasterBadge001, farcasterBadge002, farcasterShowcase001];
export default farcasterTemplates;
