/**
 * GAMING Templates - 10 Variations
 * Retro gaming theme (magenta/cyan/yellow neon)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'gaming', name: 'Gaming', primary: '#FF00FF', secondary: '#00FFFF', accent: '#FFFF00', background: '#0a0a14', text: '#ffffff', glow: '#FF00FF' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const gamingBanner001: SVGTemplate = { id: 'gaming-banner-001', name: 'Gaming Standard Banner', category: 'gaming', description: 'Standard gaming banner', palette, animations: ['pulse', 'glitch'], layout: 'hero', width: 900, height: 240, tags: ['gaming', 'banner', 'retro'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'gaming', userData: data, gaugeLabel: 'GAME STATUS', gaugeValue: 'ONLINE', badgeText: 'GAMER' }) };

export const gamingBanner002: SVGTemplate = { id: 'gaming-banner-002', name: 'Gaming Player One', category: 'gaming', description: 'Player one banner', palette: { ...palette, accent: '#00FF00' }, animations: ['pulse', 'flicker'], layout: 'hero', width: 900, height: 240, tags: ['gaming', 'banner', 'player'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'gaming', userData: data, gaugeLabel: '🎮 PLAYER 1', gaugeValue: 'READY', badgeText: '🎮 PLAYER ONE', customPalette: { accent: '#00FF00' } }) };

export const gamingBanner003: SVGTemplate = { id: 'gaming-banner-003', name: 'Gaming High Score', category: 'gaming', description: 'High score banner', palette: { ...palette, accent: '#FFD700' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['gaming', 'banner', 'score'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'gaming', userData: data, gaugeLabel: '🏆 HIGH SCORE', gaugeValue: '999999', badgeText: '🏆 HIGH SCORER', customPalette: { accent: '#FFD700' } }) };

export const gamingBanner004: SVGTemplate = { id: 'gaming-banner-004', name: 'Gaming Arcade', category: 'gaming', description: 'Arcade style banner', palette: { ...palette, primary: '#FF6B6B', secondary: '#4ECDC4' }, animations: ['pulse', 'glitch'], layout: 'hero', width: 900, height: 240, tags: ['gaming', 'banner', 'arcade'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'gaming', userData: data, gaugeLabel: '🕹️ ARCADE', gaugeValue: 'MODE', badgeText: '🕹️ ARCADE MODE', customPalette: { primary: '#FF6B6B', secondary: '#4ECDC4' } }) };

export const gamingBanner005: SVGTemplate = { id: 'gaming-banner-005', name: 'Gaming XP', category: 'gaming', description: 'XP focused banner', palette: { ...palette, primary: '#9B59B6', accent: '#3498DB' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['gaming', 'banner', 'xp'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'gaming', userData: data, gaugeLabel: '⭐ XP', gaugeValue: 'MAX', badgeText: '⭐ XP MAXED', customPalette: { primary: '#9B59B6', accent: '#3498DB' } }) };

export const gamingCard001: SVGTemplate = { id: 'gaming-card-001', name: 'Gaming Player Card', category: 'gaming', description: 'Square player card', palette, animations: ['pulse', 'glitch'], layout: 'card', width: 400, height: 400, tags: ['gaming', 'card', 'player'],
  generate: (data: UserData) => { const w=400,h=400,uid=`game-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Player 1',xp=Math.floor(parseFloat(bal||'0')/100);
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🎮 PLAYER CARD',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.35;0.2" dur="1s" repeatCount="indefinite"/></circle><circle r="50" fill="none" stroke="${palette.secondary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:40px">🎮</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="265" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.secondary}">XP: ${fmtBal(xp)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:28px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)} VOT</text>${generateFooter({address:data.address,networkLabel:'GAMING • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const gamingCard002: SVGTemplate = { id: 'gaming-card-002', name: 'Gaming Stats Card', category: 'gaming', description: 'Tall stats card', palette, animations: ['pulse', 'glitch', 'float'], layout: 'card', width: 400, height: 500, tags: ['gaming', 'card', 'stats'],
  generate: (data: UserData) => { const w=400,h=500,uid=`game-s-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Player 1',level=Math.min(99,Math.floor(parseFloat(bal||'0')/10000)+1);
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🎮 STATS CARD',width:w,palette,yOffset:25})}<g transform="translate(${w/2},115)"><circle r="50" fill="${palette.primary}" opacity="0.15"/><circle r="45" fill="none" stroke="${palette.secondary}" stroke-width="2"><animate attributeName="stroke-dasharray" values="0 283;283 0" dur="2s" repeatCount="indefinite"/></circle><text y="15" text-anchor="middle" style="font-size:40px">🎮</text></g><text x="${w/2}" y="195" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="218" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,245)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">LEVEL</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:28px;fill:${palette.accent};font-weight:bold">LV.${level}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">RANK</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.secondary}">🏆 ELITE</text></g></g><g transform="translate(30,345)"><rect width="340" height="75" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">ACHIEVEMENTS</text><g transform="translate(0,45)"><text x="50" text-anchor="middle" style="font-size:16px">🎮</text><text x="120" text-anchor="middle" style="font-size:16px">🏆</text><text x="190" text-anchor="middle" style="font-size:16px">⭐</text><text x="260" text-anchor="middle" style="font-size:16px">🔥</text><text x="310" text-anchor="middle" style="font-size:16px">💎</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const gamingBadge001: SVGTemplate = { id: 'gaming-badge-001', name: 'Gamer Badge', category: 'gaming', description: 'Compact gamer badge', palette, animations: ['pulse', 'glitch'], layout: 'minimal', width: 300, height: 100, tags: ['gaming', 'badge', 'gamer'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'Player 1').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.4;0.2" dur="1s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">🎮</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">GAMER</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">Level MAX • Elite Rank</text>`,w,h); }};

export const gamingBadge002: SVGTemplate = { id: 'gaming-badge-002', name: 'Gaming Level Badge', category: 'gaming', description: 'Circular level badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['gaming', 'badge', 'level'],
  generate: (data: UserData) => { const w=200,h=200,bal=data.holdings?.votBalance||'0',level=Math.min(99,Math.floor(parseFloat(bal||'0')/10000)+1);
    return wrapSVG(`<defs><linearGradient id="game-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#game-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="10s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="80" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.4;0.2" dur="1s" repeatCount="indefinite"/></circle><text x="100" y="95" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${level}</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">LEVEL</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:1px">GAMER</text>`,w,h); }};

export const gamingShowcase001: SVGTemplate = { id: 'gaming-showcase-001', name: 'Gaming Showcase', category: 'gaming', description: 'Full gaming showcase', palette, animations: ['pulse', 'glitch', 'gradient'], layout: 'dashboard', width: 600, height: 600, tags: ['gaming', 'showcase', 'retro'],
  generate: (data: UserData) => { const w=600,h=600,uid=`game-sh-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Player 1',level=Math.min(99,Math.floor(parseFloat(bal||'0')/10000)+1);
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🎮 GAMING SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">PLAYER PROFILE</text><g transform="translate(${w/2},185)"><circle r="80" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="80;88;80" dur="1.5s" repeatCount="indefinite"/></circle><circle r="70" fill="none" stroke="${palette.secondary}" stroke-width="2"><animate attributeName="stroke-dasharray" values="0 440;440 0" dur="3s" repeatCount="indefinite"/></circle><text y="20" text-anchor="middle" style="font-size:60px">🎮</text></g><text x="${w/2}" y="300" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="325" text-anchor="middle" style="font-size:14px;fill:${palette.accent}">LEVEL ${level} • ELITE RANK</text><g transform="translate(80,365)">${generateGauge({label:'VOT TOKENS',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'XP POINTS',value:fmtBal(Math.floor(parseFloat(bal||'0')/100)),subValue:'XP',cx:w-150,cy:60,radius:50,palette:{...palette,primary:palette.accent},uniqueId:`${uid}-xp`})}</g><g transform="translate(50,505)"><rect width="${w-100}" height="55" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">ACHIEVEMENTS</text><g transform="translate(0,40)"><text x="55" text-anchor="middle" style="font-size:16px">🎮</text><text x="130" text-anchor="middle" style="font-size:16px">🏆</text><text x="205" text-anchor="middle" style="font-size:16px">⭐</text><text x="280" text-anchor="middle" style="font-size:16px">🔥</text><text x="355" text-anchor="middle" style="font-size:16px">💎</text><text x="430" text-anchor="middle" style="font-size:16px">👑</text></g></g>${generateFooter({address:data.address,networkLabel:'GAMING • ARCADE • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const gamingTemplates: SVGTemplate[] = [gamingBanner001, gamingBanner002, gamingBanner003, gamingBanner004, gamingBanner005, gamingCard001, gamingCard002, gamingBadge001, gamingBadge002, gamingShowcase001];
export default gamingTemplates;
