/**
 * MAXX Templates - 10 Variations
 * Burn/deflationary theme (red/orange/gold)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'maxx', name: 'MAXX', primary: '#ff4444', secondary: '#ff9900', accent: '#ffcc00', background: '#1a0a0a', text: '#ffffff', glow: '#ff4444' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const maxxBanner001: SVGTemplate = { id: 'maxx-banner-001', name: 'MAXX Burn Banner', category: 'maxx', description: 'Standard MAXX burn banner', palette, animations: ['pulse', 'flicker'], layout: 'hero', width: 900, height: 240, tags: ['maxx', 'banner', 'burn'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'maxx', userData: data, gaugeLabel: '🔥 BURN STATUS', gaugeValue: 'ACTIVE', badgeText: '🔥 MAXX BURN' }) };

export const maxxBanner002: SVGTemplate = { id: 'maxx-banner-002', name: 'MAXX Inferno', category: 'maxx', description: 'Inferno edition', palette: { ...palette, primary: '#ff0000', accent: '#ff6600' }, animations: ['pulse', 'flicker'], layout: 'hero', width: 900, height: 240, tags: ['maxx', 'banner', 'inferno'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'maxx', userData: data, gaugeLabel: '🔥 INFERNO', gaugeValue: 'BLAZING', badgeText: '🔥 INFERNO MODE', customPalette: { primary: '#ff0000', accent: '#ff6600' } }) };

export const maxxBanner003: SVGTemplate = { id: 'maxx-banner-003', name: 'MAXX Phoenix', category: 'maxx', description: 'Phoenix edition', palette: { ...palette, primary: '#ff9900', secondary: '#ffcc00', accent: '#ff6600' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['maxx', 'banner', 'phoenix'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'maxx', userData: data, gaugeLabel: '🦅 PHOENIX', gaugeValue: 'RISING', badgeText: '🦅 PHOENIX EDITION', customPalette: { primary: '#ff9900', secondary: '#ffcc00', accent: '#ff6600' } }) };

export const maxxBanner004: SVGTemplate = { id: 'maxx-banner-004', name: 'MAXX Ember', category: 'maxx', description: 'Ember edition', palette: { ...palette, primary: '#cc4400', secondary: '#ff6600' }, animations: ['pulse'], layout: 'hero', width: 900, height: 240, tags: ['maxx', 'banner', 'ember'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'maxx', userData: data, gaugeLabel: '✨ EMBER', gaugeValue: 'GLOWING', badgeText: '✨ EMBER EDITION', customPalette: { primary: '#cc4400', secondary: '#ff6600' } }) };

export const maxxBanner005: SVGTemplate = { id: 'maxx-banner-005', name: 'MAXX Flame Protocol', category: 'maxx', description: 'Flame protocol', palette, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['maxx', 'banner', 'flame'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'maxx', userData: data, gaugeLabel: 'FLAME PROTOCOL', gaugeValue: 'BURNING', radarLabel: 'BURN RATE', badgeText: 'FLAME PROTOCOL' }) };

export const maxxCard001: SVGTemplate = { id: 'maxx-card-001', name: 'MAXX Burn Card', category: 'maxx', description: 'Square burn card', palette, animations: ['pulse', 'flicker'], layout: 'card', width: 400, height: 400, tags: ['maxx', 'card', 'burn'],
  generate: (data: UserData) => { const w=400,h=400,uid=`maxx-c-${Date.now()}`,bal=data.holdings?.maxxBalance||'0',name=data.displayName||data.ensName||'MAXX Burner';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔥 MAXX BURN',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.15"><animate attributeName="opacity" values="0.15;0.3;0.15" dur="1s" repeatCount="indefinite"/></circle><circle r="50" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:40px">🔥</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="280" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-size:12px;fill:${palette.secondary}">MAXX BURNED • DEFLATIONARY</text>${generateFooter({address:data.address,networkLabel:'MAXX • BURN • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const maxxCard002: SVGTemplate = { id: 'maxx-card-002', name: 'MAXX Stats Card', category: 'maxx', description: 'Tall burn stats card', palette, animations: ['pulse', 'flicker'], layout: 'card', width: 400, height: 500, tags: ['maxx', 'card', 'stats'],
  generate: (data: UserData) => { const w=400,h=500,uid=`maxx-s-${Date.now()}`,bal=data.holdings?.maxxBalance||'0',name=data.displayName||data.ensName||'MAXX Burner';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔥 BURN STATS',width:w,palette,yOffset:25})}<g transform="translate(${w/2},120)"><circle r="55" fill="${palette.primary}" opacity="0.15"/><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:45px">🔥</text></g><text x="${w/2}" y="205" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="230" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,260)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">MAXX BURNED</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">BURN RATE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">🔥 1%</text></g></g><g transform="translate(30,360)"><rect width="340" height="60" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="38" text-anchor="middle" style="font-size:11px;fill:${palette.secondary}">DEFLATIONARY PROTOCOL • AUTO-BURN</text></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const maxxBadge001: SVGTemplate = { id: 'maxx-badge-001', name: 'MAXX Burner Badge', category: 'maxx', description: 'Compact burner badge', palette, animations: ['pulse', 'flicker'], layout: 'minimal', width: 300, height: 100, tags: ['maxx', 'badge', 'burner'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'Burner').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.4;0.2" dur="1s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">🔥</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">MAXX BURNER</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">Deflationary • 1% Burn</text>`,w,h); }};

export const maxxBadge002: SVGTemplate = { id: 'maxx-badge-002', name: 'MAXX Fire Badge', category: 'maxx', description: 'Circular fire badge', palette, animations: ['rotate', 'flicker'], layout: 'centered', width: 200, height: 200, tags: ['maxx', 'badge', 'fire'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="maxx-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#maxx-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="10s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.4;0.2" dur="1s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">🔥</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">MAXX</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.accent};letter-spacing:1px">BURN</text>`,w,h); }};

export const maxxShowcase001: SVGTemplate = { id: 'maxx-showcase-001', name: 'MAXX Burn Showcase', category: 'maxx', description: 'Full MAXX burn showcase', palette, animations: ['pulse', 'flicker', 'gradient'], layout: 'dashboard', width: 600, height: 600, tags: ['maxx', 'showcase', 'burn'],
  generate: (data: UserData) => { const w=600,h=600,uid=`maxx-sh-${Date.now()}`,bal=data.holdings?.maxxBalance||'0',name=data.displayName||data.ensName||'MAXX Burner';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔥 MAXX SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">DEFLATIONARY PROTOCOL</text><g transform="translate(${w/2},190)"><circle r="85" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="85;92;85" dur="2s" repeatCount="indefinite"/></circle><circle r="75" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="20" text-anchor="middle" style="font-size:65px">🔥</text></g><text x="${w/2}" y="310" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="335" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,370)">${generateGauge({label:'MAXX BURNED',value:fmtBal(bal),subValue:'MAXX',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-maxx`})}${generateRadar({label:'BURN RATE',value:'1%',subValue:'🔥',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-burn`})}</g><g transform="translate(50,510)"><rect width="${w-100}" height="50" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="32" text-anchor="middle" style="font-size:11px;fill:${palette.secondary}">DEFLATIONARY • AUTO-BURN • 1% PER TX</text></g>${generateFooter({address:data.address,networkLabel:'MAXX • BURN • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const maxxTemplates: SVGTemplate[] = [maxxBanner001, maxxBanner002, maxxBanner003, maxxBanner004, maxxBanner005, maxxCard001, maxxCard002, maxxBadge001, maxxBadge002, maxxShowcase001];
export default maxxTemplates;
