/**
 * MCPVOT Templates - 10 Variations
 * MCP/AI protocol theme (cyan/purple/orange)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'mcpvot', name: 'MCPVOT', primary: '#00ffcc', secondary: '#8a63d2', accent: '#ff6600', background: '#0a0a1a', text: '#ffffff', glow: '#00ffcc' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const mcpvotBanner001: SVGTemplate = { id: 'mcpvot-banner-001', name: 'MCPVOT Protocol Banner', category: 'mcpvot', description: 'Standard MCPVOT protocol banner', palette, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['mcpvot', 'banner', 'protocol', 'ai'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'mcpvot', userData: data, gaugeLabel: 'MCP STATUS', gaugeValue: 'ONLINE', badgeText: 'MCP PROTOCOL' }) };

export const mcpvotBanner002: SVGTemplate = { id: 'mcpvot-banner-002', name: 'MCPVOT Neural', category: 'mcpvot', description: 'Neural network themed', palette: { ...palette, primary: '#00ff88', accent: '#ff00ff' }, animations: ['pulse', 'wave'], layout: 'hero', width: 900, height: 240, tags: ['mcpvot', 'banner', 'neural'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'mcpvot', userData: data, gaugeLabel: '🧠 NEURAL NET', gaugeValue: 'ACTIVE', badgeText: '🧠 NEURAL PROTOCOL', customPalette: { primary: '#00ff88', accent: '#ff00ff' } }) };

export const mcpvotBanner003: SVGTemplate = { id: 'mcpvot-banner-003', name: 'MCPVOT AI Agent', category: 'mcpvot', description: 'AI Agent themed', palette: { ...palette, primary: '#00ccff', secondary: '#9966ff' }, animations: ['pulse', 'float'], layout: 'hero', width: 900, height: 240, tags: ['mcpvot', 'banner', 'agent'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'mcpvot', userData: data, gaugeLabel: '🤖 AGENT STATUS', gaugeValue: 'READY', badgeText: '🤖 AI AGENT', customPalette: { primary: '#00ccff', secondary: '#9966ff' } }) };

export const mcpvotBanner004: SVGTemplate = { id: 'mcpvot-banner-004', name: 'MCPVOT x402', category: 'mcpvot', description: 'x402 facilitator banner', palette, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['mcpvot', 'banner', 'x402'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'mcpvot', userData: data, gaugeLabel: 'x402 STATUS', gaugeValue: 'ENABLED', badgeText: 'x402 FACILITATOR' }) };

export const mcpvotBanner005: SVGTemplate = { id: 'mcpvot-banner-005', name: 'MCPVOT Matrix', category: 'mcpvot', description: 'Matrix themed', palette: { ...palette, primary: '#00ff00', secondary: '#003300' }, animations: ['pulse', 'glitch'], layout: 'hero', width: 900, height: 240, tags: ['mcpvot', 'banner', 'matrix'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'mcpvot', userData: data, gaugeLabel: 'MATRIX SYNC', gaugeValue: 'LINKED', badgeText: 'MATRIX PROTOCOL', customPalette: { primary: '#00ff00', secondary: '#003300' } }) };

export const mcpvotCard001: SVGTemplate = { id: 'mcpvot-card-001', name: 'MCPVOT Protocol Card', category: 'mcpvot', description: 'Square protocol card', palette, animations: ['pulse', 'scan'], layout: 'card', width: 400, height: 400, tags: ['mcpvot', 'card', 'protocol'],
  generate: (data: UserData) => { const w=400,h=400,uid=`mcp-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'MCP Agent';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔮 MCP PROTOCOL',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="60;65;60" dur="2s" repeatCount="indefinite"/></circle><circle r="50" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-dasharray" values="0 314;314 0" dur="3s" repeatCount="indefinite"/></circle><text y="15" text-anchor="middle" style="font-size:40px">🔮</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="280" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-size:12px;fill:${palette.secondary}">VOT BALANCE • x402 ENABLED</text>${generateFooter({address:data.address,networkLabel:'MCP • x402 • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const mcpvotCard002: SVGTemplate = { id: 'mcpvot-card-002', name: 'MCPVOT Agent Card', category: 'mcpvot', description: 'Tall agent card', palette, animations: ['pulse', 'float'], layout: 'card', width: 400, height: 500, tags: ['mcpvot', 'card', 'agent'],
  generate: (data: UserData) => { const w=400,h=500,uid=`mcp-a-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'AI Agent';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🤖 AI AGENT',width:w,palette,yOffset:25})}<g transform="translate(${w/2},120)"><circle r="55" fill="${palette.secondary}" opacity="0.2"/><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-opacity" values="0.5;1;0.5" dur="1.5s" repeatCount="indefinite"/></circle><text y="15" text-anchor="middle" style="font-size:45px">🤖</text></g><text x="${w/2}" y="205" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="230" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,260)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">AGENT STATUS</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">🟢 ONLINE</text></g></g><g transform="translate(30,360)"><rect width="340" height="60" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">CAPABILITIES</text><g transform="translate(0,40)"><text x="50" text-anchor="middle" style="font-size:14px">🧠</text><text x="120" text-anchor="middle" style="font-size:14px">💬</text><text x="190" text-anchor="middle" style="font-size:14px">🔗</text><text x="260" text-anchor="middle" style="font-size:14px">⚡</text><text x="310" text-anchor="middle" style="font-size:14px">🔮</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const mcpvotBadge001: SVGTemplate = { id: 'mcpvot-badge-001', name: 'MCP Badge', category: 'mcpvot', description: 'Compact MCP badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['mcpvot', 'badge', 'mcp'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'Agent').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">🔮</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">MCP PROTOCOL</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">x402 Facilitator • AI Enabled</text>`,w,h); }};

export const mcpvotBadge002: SVGTemplate = { id: 'mcpvot-badge-002', name: 'MCPVOT AI Badge', category: 'mcpvot', description: 'Circular AI badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['mcpvot', 'badge', 'ai'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="mcp-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#mcp-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="12s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.1"><animate attributeName="opacity" values="0.1;0.2;0.1" dur="2s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">🔮</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">MCPVOT</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:1px">AI PROTOCOL</text>`,w,h); }};

export const mcpvotShowcase001: SVGTemplate = { id: 'mcpvot-showcase-001', name: 'MCPVOT Protocol Showcase', category: 'mcpvot', description: 'Full MCP protocol showcase', palette, animations: ['pulse', 'scan', 'gradient'], layout: 'dashboard', width: 600, height: 600, tags: ['mcpvot', 'showcase', 'protocol'],
  generate: (data: UserData) => { const w=600,h=600,uid=`mcp-sh-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'MCP Agent';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🔮 MCPVOT SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">MODEL CONTEXT PROTOCOL</text><g transform="translate(${w/2},190)"><circle r="85" fill="${palette.primary}" opacity="0.1"><animate attributeName="r" values="85;92;85" dur="3s" repeatCount="indefinite"/></circle><circle r="75" fill="none" stroke="${palette.primary}" stroke-width="2"><animate attributeName="stroke-dasharray" values="0 471;471 0" dur="4s" repeatCount="indefinite"/></circle><text y="20" text-anchor="middle" style="font-size:65px">🔮</text></g><text x="${w/2}" y="310" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="335" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,370)">${generateGauge({label:'VOT BALANCE',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'x402 STATUS',value:'ACTIVE',subValue:'⚡',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-x402`})}</g><g transform="translate(50,510)"><rect width="${w-100}" height="50" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">PROTOCOL FEATURES</text><g transform="translate(0,38)"><text x="60" text-anchor="middle" style="font-size:16px">🤖</text><text x="140" text-anchor="middle" style="font-size:16px">🧠</text><text x="220" text-anchor="middle" style="font-size:16px">💳</text><text x="300" text-anchor="middle" style="font-size:16px">🔗</text><text x="380" text-anchor="middle" style="font-size:16px">⚡</text><text x="440" text-anchor="middle" style="font-size:16px">🔮</text></g></g>${generateFooter({address:data.address,networkLabel:'MCPVOT • x402 • AI • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const mcpvotTemplates: SVGTemplate[] = [mcpvotBanner001, mcpvotBanner002, mcpvotBanner003, mcpvotBanner004, mcpvotBanner005, mcpvotCard001, mcpvotCard002, mcpvotBadge001, mcpvotBadge002, mcpvotShowcase001];
export default mcpvotTemplates;
