/**
 * VOT Templates - 10 Variations
 * Core VOT protocol theme (cyan/orange/magenta)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner, CATEGORY_PALETTES } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = {
  id: 'vot', name: 'VOT', primary: '#00ffcc', secondary: '#ff6600', accent: '#cc00ff',
  background: '#0a0a0a', text: '#ffffff', glow: '#00ffcc'
};

const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const votBanner001: SVGTemplate = { id: 'vot-banner-001', name: 'VOT Standard Banner', category: 'vot', description: 'Standard VOT protocol banner', palette, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['vot', 'banner', 'standard'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'vot', userData: data, gaugeLabel: 'VOT STATUS', gaugeValue: 'ACTIVE', badgeText: 'VOT PROTOCOL' }) };

export const votBanner002: SVGTemplate = { id: 'vot-banner-002', name: 'VOT Whale Tier', category: 'vot', description: 'Whale tier banner (1M+ VOT)', palette: { ...palette, accent: '#FFD700' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['vot', 'banner', 'whale'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'vot', userData: data, gaugeLabel: '🐋 WHALE TIER', gaugeValue: 'ELITE', badgeText: '🐋 WHALE HOLDER', customPalette: { accent: '#FFD700' } }) };

export const votBanner003: SVGTemplate = { id: 'vot-banner-003', name: 'VOT Diamond Hands', category: 'vot', description: 'Diamond hands banner', palette: { ...palette, primary: '#00BFFF', accent: '#ADD8E6' }, animations: ['pulse', 'sparkle'], layout: 'hero', width: 900, height: 240, tags: ['vot', 'banner', 'diamond'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'vot', userData: data, gaugeLabel: '💎 DIAMOND', gaugeValue: 'HANDS', badgeText: '💎 DIAMOND HANDS', customPalette: { primary: '#00BFFF', accent: '#ADD8E6' } }) };

export const votBanner004: SVGTemplate = { id: 'vot-banner-004', name: 'VOT Burn Edition', category: 'vot', description: 'Burn themed banner', palette: { ...palette, primary: '#ff4444', secondary: '#ff9900', accent: '#ffcc00' }, animations: ['pulse', 'flicker'], layout: 'hero', width: 900, height: 240, tags: ['vot', 'banner', 'burn'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'vot', userData: data, gaugeLabel: '🔥 BURN', gaugeValue: 'ACTIVE', badgeText: '🔥 BURN EDITION', customPalette: { primary: '#ff4444', secondary: '#ff9900', accent: '#ffcc00' } }) };

export const votBanner005: SVGTemplate = { id: 'vot-banner-005', name: 'VOT Protocol Edition', category: 'vot', description: 'x402 protocol banner', palette, animations: ['pulse', 'scan'], layout: 'hero', width: 900, height: 240, tags: ['vot', 'banner', 'x402'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'vot', userData: data, gaugeLabel: 'x402 STATUS', gaugeValue: 'ENABLED', badgeText: 'x402 PROTOCOL' }) };

export const votCard001: SVGTemplate = { id: 'vot-card-001', name: 'VOT Square Card', category: 'vot', description: 'Square VOT card', palette, animations: ['pulse'], layout: 'card', width: 400, height: 400, tags: ['vot', 'card', 'square'],
  generate: (data: UserData) => { const w=400,h=400,uid=`vot-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'VOT Holder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🟠 VOT PROTOCOL',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.15"><animate attributeName="opacity" values="0.15;0.25;0.15" dur="2s" repeatCount="indefinite"/></circle><circle r="50" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:40px">🟠</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="280" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-size:12px;fill:${palette.secondary}">VOT BALANCE • x402 ENABLED</text>${generateFooter({address:data.address,networkLabel:'VOT • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const votCard002: SVGTemplate = { id: 'vot-card-002', name: 'VOT Profile Card', category: 'vot', description: 'Tall VOT profile card', palette, animations: ['pulse', 'float'], layout: 'card', width: 400, height: 500, tags: ['vot', 'card', 'profile'],
  generate: (data: UserData) => { const w=400,h=500,uid=`vot-p-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'VOT Holder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🟠 VOT PROFILE',width:w,palette,yOffset:25})}<g transform="translate(${w/2},120)"><circle r="55" fill="${palette.primary}" opacity="0.15"/><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:45px">🟠</text></g><text x="${w/2}" y="205" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="230" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,260)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">STATUS</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">🟢 ACTIVE</text></g></g><g transform="translate(30,360)"><rect width="340" height="60" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">CREDENTIALS</text><g transform="translate(0,40)"><text x="50" text-anchor="middle" style="font-size:14px">🟠</text><text x="120" text-anchor="middle" style="font-size:14px">💎</text><text x="190" text-anchor="middle" style="font-size:14px">🔥</text><text x="260" text-anchor="middle" style="font-size:14px">⚡</text><text x="310" text-anchor="middle" style="font-size:14px">🏆</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const votBadge001: SVGTemplate = { id: 'vot-badge-001', name: 'VOT Badge', category: 'vot', description: 'Compact VOT badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['vot', 'badge', 'compact'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'Holder').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">🟠</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">VOT PROTOCOL</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">x402 Enabled • Base Chain</text>`,w,h); }};

export const votBadge002: SVGTemplate = { id: 'vot-badge-002', name: 'VOT Holder Badge', category: 'vot', description: 'Circular holder badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['vot', 'badge', 'circular'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="vot-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#vot-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="12s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">🟠</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.primary};font-weight:bold">VOT</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:1px">HOLDER</text>`,w,h); }};

export const votShowcase001: SVGTemplate = { id: 'vot-showcase-001', name: 'VOT Full Showcase', category: 'vot', description: 'Full VOT showcase', palette, animations: ['pulse', 'gradient', 'float'], layout: 'dashboard', width: 600, height: 600, tags: ['vot', 'showcase', 'full'],
  generate: (data: UserData) => { const w=600,h=600,uid=`vot-s-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'VOT Holder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'🟠 VOT SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">VOT PROTOCOL</text><g transform="translate(${w/2},190)"><circle r="85" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="85;92;85" dur="3s" repeatCount="indefinite"/></circle><circle r="75" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="20" text-anchor="middle" style="font-size:65px">🟠</text></g><text x="${w/2}" y="310" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="335" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,370)">${generateGauge({label:'VOT BALANCE',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'x402 STATUS',value:'ACTIVE',subValue:'⚡',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-x402`})}</g><g transform="translate(50,510)"><rect width="${w-100}" height="50" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">PROTOCOL FEATURES</text><g transform="translate(0,38)"><text x="60" text-anchor="middle" style="font-size:16px">🟠</text><text x="140" text-anchor="middle" style="font-size:16px">💎</text><text x="220" text-anchor="middle" style="font-size:16px">🔥</text><text x="300" text-anchor="middle" style="font-size:16px">⚡</text><text x="380" text-anchor="middle" style="font-size:16px">🏆</text><text x="440" text-anchor="middle" style="font-size:16px">🔗</text></g></g>${generateFooter({address:data.address,networkLabel:'VOT • x402 • BASE',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const votTemplates: SVGTemplate[] = [votBanner001, votBanner002, votBanner003, votBanner004, votBanner005, votCard001, votCard002, votBadge001, votBadge002, votShowcase001];
export default votTemplates;
