/**
 * WARPLET Templates - 10 Variations
 * Premium Warplet theme (purple/cyan/pink)
 */

import type { UserData, SVGTemplate, ColorPalette } from '../types';
import { generateIdentityBanner } from '../banner-template';
import { generateHeader, generateFooter, formatAddress, generateGauge, generateRadar, generateBackground } from '../components';

const palette: ColorPalette = { id: 'warplet', name: 'Warplet', primary: '#8B5CF6', secondary: '#06B6D4', accent: '#EC4899', background: '#0f0a1a', text: '#ffffff', glow: '#8B5CF6' };
const wrapSVG = (c: string, w: number, h: number) => `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;
const fmtBal = (b?: string | number) => { if (!b) return '---'; const n = typeof b === 'string' ? parseFloat(b) : b; if (isNaN(n)) return '---'; return n >= 1e6 ? `${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `${(n/1e3).toFixed(1)}K` : n.toFixed(0); };

export const warpletBanner001: SVGTemplate = { id: 'warplet-banner-001', name: 'Warplet Premium Banner', category: 'warplet', description: 'Standard Warplet premium banner', palette, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['warplet', 'banner', 'premium'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'warplet', userData: data, gaugeLabel: '👑 PREMIUM', gaugeValue: 'ACTIVE', badgeText: '👑 WARPLET' }) };

export const warpletBanner002: SVGTemplate = { id: 'warplet-banner-002', name: 'Warplet Diamond', category: 'warplet', description: 'Diamond edition', palette: { ...palette, accent: '#00BFFF' }, animations: ['pulse', 'sparkle'], layout: 'hero', width: 900, height: 240, tags: ['warplet', 'banner', 'diamond'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'warplet', userData: data, gaugeLabel: '💎 DIAMOND', gaugeValue: 'TIER', badgeText: '💎 DIAMOND EDITION', customPalette: { accent: '#00BFFF' } }) };

export const warpletBanner003: SVGTemplate = { id: 'warplet-banner-003', name: 'Warplet OG', category: 'warplet', description: 'OG edition', palette: { ...palette, accent: '#FFD700' }, animations: ['pulse', 'gradient'], layout: 'hero', width: 900, height: 240, tags: ['warplet', 'banner', 'og'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'warplet', userData: data, gaugeLabel: '⭐ OG STATUS', gaugeValue: 'VERIFIED', badgeText: '⭐ OG EDITION', customPalette: { accent: '#FFD700' } }) };

export const warpletBanner004: SVGTemplate = { id: 'warplet-banner-004', name: 'Warplet Elite', category: 'warplet', description: 'Elite edition', palette: { ...palette, primary: '#4B0082' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['warplet', 'banner', 'elite'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'warplet', userData: data, gaugeLabel: '🏆 ELITE', gaugeValue: 'MEMBER', badgeText: '🏆 ELITE EDITION', customPalette: { primary: '#4B0082' } }) };

export const warpletBanner005: SVGTemplate = { id: 'warplet-banner-005', name: 'Warplet Chrome', category: 'warplet', description: 'Chrome edition', palette: { ...palette, primary: '#C0C0C0', secondary: '#A0A0A0', accent: '#E0E0E0' }, animations: ['pulse', 'shimmer'], layout: 'hero', width: 900, height: 240, tags: ['warplet', 'banner', 'chrome'],
  generate: (data: UserData) => generateIdentityBanner({ category: 'warplet', userData: data, gaugeLabel: '🔘 CHROME', gaugeValue: 'MODE', badgeText: '🔘 CHROME EDITION', customPalette: { primary: '#C0C0C0', secondary: '#A0A0A0', accent: '#E0E0E0' } }) };

export const warpletCard001: SVGTemplate = { id: 'warplet-card-001', name: 'Warplet Holder Card', category: 'warplet', description: 'Square holder card', palette, animations: ['pulse', 'shimmer'], layout: 'card', width: 400, height: 400, tags: ['warplet', 'card', 'holder'],
  generate: (data: UserData) => { const w=400,h=400,uid=`warp-c-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Warplet Holder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'👑 WARPLET',width:w,palette,yOffset:25})}<g transform="translate(${w/2},140)"><circle r="60" fill="${palette.primary}" opacity="0.15"><animate attributeName="opacity" values="0.15;0.25;0.15" dur="2s" repeatCount="indefinite"/></circle><circle r="50" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:40px">👑</text></g><text x="${w/2}" y="230" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="280" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:32px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><text x="${w/2}" y="305" text-anchor="middle" style="font-size:12px;fill:${palette.secondary}">VOT BALANCE • PREMIUM</text>${generateFooter({address:data.address,networkLabel:'WARPLET • PREMIUM',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const warpletCard002: SVGTemplate = { id: 'warplet-card-002', name: 'Warplet Premium Card', category: 'warplet', description: 'Tall premium card', palette, animations: ['pulse', 'shimmer', 'float'], layout: 'card', width: 400, height: 500, tags: ['warplet', 'card', 'premium'],
  generate: (data: UserData) => { const w=400,h=500,uid=`warp-p-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Warplet Holder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'👑 PREMIUM',width:w,palette,yOffset:25})}<g transform="translate(${w/2},120)"><circle r="55" fill="${palette.primary}" opacity="0.15"/><circle r="48" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="15" text-anchor="middle" style="font-size:45px">👑</text></g><text x="${w/2}" y="205" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:20px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="230" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(30,260)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">VOT BALANCE</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.accent};font-weight:bold">${fmtBal(bal)}</text><g transform="translate(180,0)"><rect width="160" height="70" rx="8" fill="${palette.primary}" opacity="0.1"/><text x="80" y="25" text-anchor="middle" style="font-size:10px;fill:${palette.secondary}">TIER</text><text x="80" y="55" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:18px;fill:${palette.primary}">👑 PREMIUM</text></g></g><g transform="translate(30,360)"><rect width="340" height="60" rx="8" fill="${palette.primary}" opacity="0.05"/><text x="170" y="18" text-anchor="middle" style="font-size:9px;fill:${palette.secondary};letter-spacing:2px">PERKS</text><g transform="translate(0,40)"><text x="50" text-anchor="middle" style="font-size:14px">👑</text><text x="120" text-anchor="middle" style="font-size:14px">💎</text><text x="190" text-anchor="middle" style="font-size:14px">⚡</text><text x="260" text-anchor="middle" style="font-size:14px">🔮</text><text x="310" text-anchor="middle" style="font-size:14px">🏆</text></g></g>${generateFooter({address:data.address,width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const warpletBadge001: SVGTemplate = { id: 'warplet-badge-001', name: 'Warplet OG Badge', category: 'warplet', description: 'Compact OG badge', palette, animations: ['pulse'], layout: 'minimal', width: 300, height: 100, tags: ['warplet', 'badge', 'og'],
  generate: (data: UserData) => { const w=300,h=100,name=(data.displayName||data.ensName||'OG').slice(0,12);
    return wrapSVG(`<rect width="${w}" height="${h}" fill="${palette.background}" rx="8"/><rect x="2" y="2" width="${w-4}" height="${h-4}" fill="none" stroke="${palette.primary}" stroke-width="1" rx="6" opacity="0.6"/><g transform="translate(50,50)"><circle r="30" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text y="10" text-anchor="middle" style="font-size:28px">👑</text></g><text x="100" y="35" style="font-family:'Orbitron',sans-serif;font-size:14px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="100" y="55" style="font-family:'Orbitron',sans-serif;font-size:11px;fill:${palette.primary}">WARPLET OG</text><text x="100" y="80" style="font-size:9px;fill:${palette.secondary}">Premium Member • Verified</text>`,w,h); }};

export const warpletBadge002: SVGTemplate = { id: 'warplet-badge-002', name: 'Warplet Verified Badge', category: 'warplet', description: 'Circular verified badge', palette, animations: ['rotate', 'pulse'], layout: 'centered', width: 200, height: 200, tags: ['warplet', 'badge', 'verified'],
  generate: (data: UserData) => { const w=200,h=200;
    return wrapSVG(`<defs><linearGradient id="warp-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${palette.primary}"/><stop offset="50%" stop-color="${palette.secondary}"/><stop offset="100%" stop-color="${palette.accent}"/></linearGradient></defs><circle cx="100" cy="100" r="95" fill="none" stroke="url(#warp-grad)" stroke-width="3"><animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" dur="12s" repeatCount="indefinite"/></circle><circle cx="100" cy="100" r="80" fill="${palette.background}" stroke="${palette.primary}" stroke-width="2"/><circle cx="100" cy="85" r="35" fill="${palette.primary}" opacity="0.2"><animate attributeName="opacity" values="0.2;0.3;0.2" dur="2s" repeatCount="indefinite"/></circle><text x="100" y="98" text-anchor="middle" style="font-size:40px">✓</text><text x="100" y="145" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:12px;fill:${palette.primary};font-weight:bold">WARPLET</text><text x="100" y="162" text-anchor="middle" style="font-size:10px;fill:${palette.accent};letter-spacing:1px">VERIFIED</text>`,w,h); }};

export const warpletShowcase001: SVGTemplate = { id: 'warplet-showcase-001', name: 'Warplet Premium Showcase', category: 'warplet', description: 'Full Warplet showcase', palette, animations: ['pulse', 'shimmer', 'gradient'], layout: 'dashboard', width: 600, height: 600, tags: ['warplet', 'showcase', 'premium'],
  generate: (data: UserData) => { const w=600,h=600,uid=`warp-sh-${Date.now()}`,bal=data.holdings?.votBalance||'0',name=data.displayName||data.ensName||'Warplet Holder';
    return wrapSVG(`${generateBackground({width:w,height:h,palette,uniqueId:uid})}${generateHeader({protocolName:'👑 WARPLET SHOWCASE',width:w,palette,yOffset:30})}<text x="${w/2}" y="75" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:26px;fill:${palette.primary};font-weight:bold">PREMIUM MEMBERSHIP</text><g transform="translate(${w/2},190)"><circle r="85" fill="${palette.primary}" opacity="0.15"><animate attributeName="r" values="85;92;85" dur="3s" repeatCount="indefinite"/></circle><circle r="75" fill="none" stroke="${palette.primary}" stroke-width="2"/><text y="20" text-anchor="middle" style="font-size:65px">👑</text></g><text x="${w/2}" y="310" text-anchor="middle" style="font-family:'Orbitron',sans-serif;font-size:22px;fill:${palette.text};font-weight:bold">${name.toUpperCase()}</text><text x="${w/2}" y="335" text-anchor="middle" style="font-size:11px;fill:${palette.secondary};font-family:monospace">${formatAddress(data.address)}</text><g transform="translate(80,370)">${generateGauge({label:'VOT BALANCE',value:fmtBal(bal),subValue:'VOT',cx:70,cy:60,radius:50,palette,uniqueId:`${uid}-vot`})}${generateRadar({label:'PREMIUM',value:'ACTIVE',subValue:'👑',cx:w-150,cy:60,radius:50,palette,uniqueId:`${uid}-prem`})}</g><g transform="translate(50,510)"><rect width="${w-100}" height="50" rx="8" fill="${palette.primary}" opacity="0.08"/><text x="${(w-100)/2}" y="18" text-anchor="middle" style="font-size:10px;fill:${palette.secondary};letter-spacing:2px">HOLDER BENEFITS</text><g transform="translate(0,38)"><text x="60" text-anchor="middle" style="font-size:16px">👑</text><text x="140" text-anchor="middle" style="font-size:16px">💎</text><text x="220" text-anchor="middle" style="font-size:16px">⚡</text><text x="300" text-anchor="middle" style="font-size:16px">🔮</text><text x="380" text-anchor="middle" style="font-size:16px">🏆</text><text x="440" text-anchor="middle" style="font-size:16px">✓</text></g></g>${generateFooter({address:data.address,networkLabel:'WARPLET • PREMIUM • VERIFIED',width:w,height:h,palette,bottomOffset:25})}`,w,h); }};

export const warpletTemplates: SVGTemplate[] = [warpletBanner001, warpletBanner002, warpletBanner003, warpletBanner004, warpletBanner005, warpletCard001, warpletCard002, warpletBadge001, warpletBadge002, warpletShowcase001];
export default warpletTemplates;
